[build]
  command = "pnpm install && pnpm build"
  functions = "server"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "22"
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
